version: "3"
services:
  ui:
    container_name: crawlyui.com
    command: /crawlyui/bin/ec start
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIX_ENV: prod
      SECRET_KEY_BASE: "UDWLdQ4flBCR2W7j1ECKj4VZUtop6st4+OBoCXjJMIn0TPDO++xyxbzOR1qN7pK7"
      RELEASE_COOKIE: "123"
      NODE_NAME: "ui@crawlyui.com"
      POOL_SIZE: 10
      DATABASE_URL: ${DATABASE_URL:-ecto://postgres:example@crawlyuidb/crawlyui}

    ports:
      - 80:4000

  postgres:
    restart: always
    image: postgres:11.4-alpine
    container_name: crawlyuidb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGPASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: crawlyui

  shops_worker:
    stdin_open: true
    tty: true
    container_name: shops_worker.com
    command:  iex --cookie 123 --name shops_worker@worker.com -S mix
    build:
      context: "examples/shops"
      dockerfile: Dockerfile
    environment:
      UI_NODE: "ui@crawlyui.com"

  cars_worker:
    stdin_open: true
    tty: true
    container_name: cars_worker.com
    command:  iex --cookie 123 --name cars_worker@worker.com -S mix
    build:
      context: "examples/cars"
      dockerfile: Dockerfile
    environment:
      UI_NODE: "ui@crawlyui.com"
    volumes:
      - images:/examples/cars/images
      - output:/examples/cars/output

volumes:
  images:
  output:
