version: "3"
services:
  ui:
    container_name: crawlyui.com
    command: /crawlyui/bin/ec start
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIX_ENV: prod
      SECRET_KEY_BASE: "UDWLdQ4flBCR2W7j1ECKj4VZUtop6st4+OBoCXjJMIn0TPDO++xyxbzOR1qN7pK7"
      RELEASE_COOKIE: "123"
      NODE_NAME: "ui@crawlyui.com"
      POOL_SIZE: 10
      DATABASE_URL: ${DATABASE_URL:-ecto://postgres:example@crawlyuidb/crawlyui}

    ports:
      - 80:4000

  postgres:
    image: postgres:11.4-alpine
    container_name: crawlyuidb
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
      PGPASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: crawlyui

  worker:
    stdin_open: true
    tty: true
    container_name: worker.com
    command:  iex --cookie 123 --name worker@worker.com -S mix
    build:
      context: "examples"
      dockerfile: Dockerfile
    environment:
      UI_NODE: "ui@crawlyui.com"

